#!/usr/bin/env node
// generate-llms.mjs — regenerate llms.txt from the built dist/ tree.
//
// Guarantees the file contains ONLY live URLs (no dead links, trailing
// slashes everywhere). Aliased URL families are listed once, preferring the
// canonical form:
//   /faq/q/<id>/  and  /qa/<id>/  (meta-refresh aliases)  -> /kb/q/<id>/
//
// Usage: node scripts/generate-llms.mjs [distDir] [outFile]
//   default distDir = dist/ , outFile = dist/llms.txt
import fs from "node:fs";
import path from "node:path";

const distDir = path.resolve(process.argv[2] ?? "dist");
const outFile = process.argv[3] ?? path.join(distDir, "llms.txt");

const SKIP_DIRS = new Set([
  "_astro", "assets", "avatars", "articles", "images", "hvac", "admin",
  "carousel", "infocard",
]);
// Path prefixes to drop: /faq/q/ + /qa/* are aliases of /kb/q/ (meta-refresh
// 200s), /about/ and /admin/ are non-content.
const SKIP_PREFIXES = ["/faq/q/", "/qa/", "/about/", "/admin/"];
const SKIP_FILES = new Set([
  "404.html", "index.html", "robots.txt", "llms.txt",
  "favicon.ico", "favicon.png", "favicon.svg", "logo.png", "rss.xml",
]);
const NON_PAGE_EXT = new Set([
  ".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg", ".css", ".js", ".json",
  ".xml", ".webmanifest", ".txt", ".pdf", ".map", ".woff", ".woff2", ".ttf",
  ".ico",
]);

const SECTION_TITLES = [
  ["/a/", "## Articles"],
  ["/faq/", "## FAQ (categories)"],
  ["/kb/q/", "## Knowledge Base Q&A"],
  ["/kb/", "## Knowledge Base Categories"],
  ["/x/", "## X Post Archive"],
  ["/", "## Hub Pages"],
];

function walk(dir, rel, acc) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const relPath = rel ? `${rel}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      walk(path.join(dir, entry.name), relPath, acc);
    } else if (entry.isFile() && entry.name === "index.html") {
      acc.push(relPath.slice(0, -"index.html".length));
    }
  }
}

function toUrl(relDir) {
  return `https://ai.xinca.com/${relDir}`;
}

const pageDirs = [];
walk(distDir, "", pageDirs);

// Only keep pages (dirs with index.html), sorted by section order.
const bySection = new Map();
for (const sec of SECTION_TITLES) bySection.set(sec[0], []);

const buckets = new Map(SECTION_TITLES.map(([p, t]) => [p, []]));
for (const d of pageDirs) {
  const url = toUrl(d);
  const key = "/" + d;
  if (SKIP_PREFIXES.some((p) => key.startsWith(p))) continue;
  let placed = false;
  for (const [prefix, list] of buckets) {
    if (prefix === "/") {
      if (key === "/") { list.push(url); placed = true; break; }
      continue;
    }
    if (key.startsWith(prefix) && key !== prefix.slice(0, -1)) {
      list.push(url);
      placed = true;
      break;
    }
  }
  if (!placed) buckets.get("/").push(url); // fallback: hubs section
}

const lines = [
  "# ai.xinca.com — HVAC Controls Engineering Knowledge Hub",
  "# LLMs.txt for AI/LLM ingestion — auto-generated by scripts/generate-llms.mjs",
  `# Generated: ${new Date().toISOString().slice(0, 10)}`,
  "",
];
for (const [prefix, title] of SECTION_TITLES) {
  const urls = buckets.get(prefix);
  if (!urls.length) continue;
  lines.push(title, "");
  for (const u of urls) lines.push(u);
  lines.push("");
}

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, lines.join("\n"));
console.log(`llms.txt written: ${outFile} (${pageDirs.length} pages, ` +
            `${lines.filter((l) => l.startsWith("https://")).length} URLs)`);
